package com.example.emall_ec.main.index

/**
 * Created by lixiang on 2018/2/28.
 */
enum class VideoDetailFields {
    CLOUD, DURATION, GEO, IMAGEDETAILURL, LATITUDE, LONGITUDE, ORIGINALPRICE, PRODUCTID, PROMOTIONDESCRIPTION, PROMOTIONTYPE, RESOLUTION, ROLLSATELLITEANGLEMAJOR, SALEPRICE, SATELLITEID, SENSOR, SERVICEDESCRIPTION, SIZE, STARTTIME, TITLE, VIDEOPATH
}